services:
  jadoo:
    image: ghcr.io/nilenso/jadoo:latest
    container_name: jadoo
    restart: unless-stopped
    environment:
      CONFIG_PATH: /app/config.toml
    volumes:
      - ./config.toml:/app/config.toml:ro
      - jadoo-data:/app/data

volumes:
  jadoo-data:
